name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve || true

      - name: Deploy App via SSM
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)

          echo "Instances: $INSTANCE_IDS"

          TARGETS=$(echo $INSTANCE_IDS | sed 's/ /,/g')

          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=$TARGETS" \
            --parameters '{"commands":[
            "cat <<EOF > /var/www/html/index.html  
            <!DOCTYPE html>
            <html>
            <head>
              <title>DevOps Project 🚀</title>
              <style>
                body { font-family: Arial; text-align: center; background: #0f172a; color: white; }
                h1 { color: #38bdf8; }
                .box { margin-top: 50px; padding: 20px; border: 1px solid #38bdf8; border-radius: 10px; display: inline-block; }
              </style>
            </head>
            <body>
              <h1> CI/CD Deployment Successful</h1>
              <div class=\"box\">
                <p><b>Instance:</b> $(hostname)</p>
                <p><b>Deployed via:</b> GitHub Actions</p>
                <p><b>Server:</b> Nginx</p>
                <p><b>Status:</b> Running ✅</p>
              </div>
            </body>
            </html>
            EOF",
            "systemctl restart nginx"
            ]}'
